# --------------------------- Default file paths ---------------------------- #
SAMPLE_MANIFEST: 'config/sample_manifest.tsv'

RESULTS_DIR: 'results'
FIGURE_DIR: 'results/figures'
QC_DIR: 'results/quality_control'

EXTERNAL_DATA_DIR: 'resources/external'
FASTQ_DIR: 'resources/raw_data'

LOG_DIR: 'logs'
TEMP_DIR: 'temp_data'
REPORT_DIR: 'reports'

# --------------------------- Handles ---------------------------- #

SUBSET_COLUMN: ''
SUBSET_VALUE: ''

# --------------------------- Params for raw processing ---------------------------- #

TRIM_GALORE:
    HISEQ: '--quality 20'
    NOVASEQ: '--2colour 20'
    NEXTSEQ: '--2colour 20'

    LENGTH: 20
    CLIP_5: 1
    CLIP_3: 1
    EXTRA: ""
#    lenght: 20

SLAM:
    MAX_LENGTH: 100 # [also used for alleyoop]
# -- Filter --
    MIN_MAP_QUALITY: 2 # (default: 2)
    MIN_IDENTITY: 0.95 # (default: 0.95)
    MAX_MISMATCH: -1 # (default: -1)
# -- SNP --
    VAR_MIN_COVERAGE: 10 # (default: 10)
    VAR_FRACTION: 0.2 # for diploids use 0.2 # (default: 0.8)
# -- Count --
    CONVERSION_THRESHOLD: 2 # (default: 1)
    MIN_QUAL: 27 # min base quality for T -> C conversions (default:27) [also used for alleyoop]

# --------------------------- Params for downstream analysis ---------------------------- #

ENSEMBL:
    VERSION: 108

DESEQ2:
    SUBSET_FILTER: '' # leave empty if no subgroup requiered, or fill with corresponding group on sample_manifest.tsv
    PVAL_THRESHOLD: 0.05
    # PADJ_THRESHOLD: 1
    # PADJ_THRESHOLD: 0.05