# proj: "Test_Exons_NoScaffold_NoPseudo"
proj: "Test_Exons_TC2_Other"
data_dir: "HL_slam_seq_test_20220803"

samples:
    dir: "/home/ife/paulina.rosales/data/HL_slam_seq_test_20220803"
    # limsCSV: "/home/ife/paulina.rosales/data/HL_slam_seq_test_20220803/Project_469_lims.csv"
    manifest: "/home/ife/paulina.rosales/data/HL_slam_seq_test_20220803/sample_manifest.tsv"

# Genome infoNoScaffold
genome_build: "m38"    #human=hg38, mouse=m38
gencode_version: "25" # human=38, mouse=25
ensembl_version: 108

# Raw processing
trim_galore:
    length: 20
    clip_5: 1
    clip_3: 1
    quality: "-q 28" # --2colour 28 
    extra_params: ""

slam:
    max_len: 100
    # count
    conversion_threshold: 2 # -c 
    min_qual: 27 # min base quality for T -> C conversions (default:27)
    # snp
    variant_fraction: 0.2 # for diploids = 0.2

deseq2:
    subgroup_filter: "" # leave empty if no subgroup requiered, or fill with corresponding group on sample_manifest.tsv
    pvalue_threshold: 0.05

# DE Analysis
# transformation: "vst" # only log2, vst or rlog
# threshold:
#     log2FC: 1
#     padj: 0.05
